#! /bin/bash
### BEGIN INIT INFO
# Provides:          riemann-passenger
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:
# Default-Stop:      0 1 6
# Short-Description: Riemann passenger stats collector
# chkconfig: - 80 15
# Description: Riemann passenger stats collector
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions


DAEMON=/usr/bin/riemann-passenger
NAME=riemann-passenger
PID_FILE=${PIDFILE:-/var/run/${NAME}.pid}
LOCK_FILE=${LOCKFILE:-/var/lock/subsys/${NAME}}
NFILES=${NFILES:-32768}
export RBENV_VERSION="2.2.5"
## OT servers:
## DAEMON_OPTS="-h 10.11.5.7"
## if on a non-OT server
DAEMON_OPTS="-h 72.13.0.90 -p 443"

start() {
    echo -n $"Starting ${NAME}: "
    ulimit -n $NFILES
    daemonize  -p $PID_FILE -l $LOCK_FILE $DAEMON $DAEMON_OPTS
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
    return $RETVAL
}

reload() {
    echo -n $"Reloading ${NAME}: "
    killproc -p ${PID_FILE} $DAEMON -1
    RETVAL=$?
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping ${NAME}: "
    killproc -p ${PID_FILE} -d 10 $DAEMON
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${LOCK_FILE} ${PID_FILE}
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status -p ${PID_FILE} $DAEMON
        RETVAL=$?
        ;;
    reload|force-reload)
        reload
        ;;
    restart)
        stop
        start
        ;;
    *)
        N=/etc/init.d/${NAME}
        echo "Usage: $N {start|stop|status|restart|force-reload}" >&2
        RETVAL=2
        ;;
esac

exit $RETVAL
